name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm ci
        working-directory: ./GPTPullRequestReview

      - run: npm run build
        working-directory: ./GPTPullRequestReview